networks:
  containet:
    driver: bridge


version: "2.4"
services:

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=Abcabc123!
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    networks:
      - containet
    ports:
      - 5601:5601
    depends_on:
      - elastic-search

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elastic-search
    networks:
      - containet
    ports:
      - 9200:9200
    environment:
      - NETWORK_HOST=http://elastic-search:9200
      - node.name=es01
      - cluster.name=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "indices.query.bool.max_clause_count=10000000"
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
